---
# See https://pre-commit.com/hooks.html for info on hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: (base:repo) debug-statements
        args: ['--maxkb=5000']
        stages: [pre-commit]
      - id: check-ast
        name: (base:repo) check-ast
        stages: [pre-commit]
      - id: check-toml
        name: (base:repo) check-toml
        stages: [pre-commit]
      - id: check-yaml
        name: (base:repo) check-yaml
        stages: [pre-commit]
      - id: debug-statements
        name: (base:repo) debug-statements
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        name: (base:repo) ruff
        args: ["--fix"]
        stages: [pre-commit]
      - id: ruff-format
        name: (base:repo) ruff-format
        stages: [pre-commit]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2
    hooks:
      - id: sphinx-lint
        name: (docs:repo) sphinx-lint
        stages: [pre-commit]
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.13
    hooks:
      - id: biome-check
        name: (webtools:repo) biome-check
        args: ["./webtools/src", "--config-path=./webtools/biome.json"]
        exclude: "^docs/"
        stages: [pre-commit]
